name: CI

on:
  push:
    branches:
      - master

  pull_request:

jobs:
  
  test:
    strategy:
      matrix:
        PHP: [56, 73, 74, 80]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Prepare code
        env:
          PHP_VERSION: ${{ matrix.PHP }}
        run: |
          touch .env
          echo "WHATICKET_BASEURL=${ secrets.WHATICKET_BASEURL }" >> .env
          echo "WHATICKET_TOKEN=${ secrets.WHATICKET_TOKEN }" >> .env
          echo "WHATICKET_NUMBER=${ secrets.WHATICKET_NUMBER }" >> .env
          echo "WHATICKET_ID=${ secrets.WHATICKET_ID }" >> .env
          echo "PHP_VERSION=$PHP_VERSION" >> .env

      - name: Prepare environment
        run: |
          docker-compose up -d
          echo $(docker run -t --network github jwilder/dockerize -wait tcp://php:9000 -timeout 120s)
          docker-compose ps
          docker-compose logs php

      - name: Install PHP Stan
        if: matrix.PHP != '56'
        run: |
          docker-compose exec -T php composer require phpstan/phpstan --dev

      - name: Run PHP Unit
        run: |
          docker-compose exec -T php composer test

      - name: Run PHP Stan
        if: matrix.PHP != '56'
        run: |
          docker-compose exec -T php composer analyse

      - name: Run PHP CS Fixer
        if: matrix.PHP != '56'
        run: |
          docker-compose exec -T php composer fix:ci